### ISSUE TITLE
Create Handout with equipment for mesh nodes

### ISSUE THREAD

**Issue by dcwalk** [tomeshnet/p2p-internet-workshop#26]
This feedback came up at the install night Mar 22 and workshop run through briefly Apr 5!
Would also be good to list places where they can buy locally (Creatron! Online):

- Raspberry Pi 3 
- SD Card
- Power Adapter
- Antenna + Male f-pin thing??? (like this? https://www.amazon.com/Crazepony-Antenna-Extension-RP-SMA-Adapter/dp/B01DNMA9YI?ref_=fspcr_pl_dp_3_2234127011) @benhylau 
- Optional: A USB WiFi adapter with 802.11s Mesh Point support, such as the TP-LINK TL-WN722N

@benhylau  can you clarify my ambiquity?
I can draft this for Tuesday.

**Comment by benhylau** [comment]
Hmm... a little tricky because the new versions of TP-LINK TL-WN722N no longer supports mesh point :( so it's better to take the WiFi adapters we ordered from Toplinkst, but you cannot find that locally. 

@darkdrgn2k do you have a suggestion for a low cost and locally available mesh point adapter?

**Comment by dcwalk** [comment]
Hey, is this still something we want to pull together @benhylau and @darkdrgn2k ?

**Comment by darkdrgn2k** [comment]
Locally

**Raspberry pi** -Creation Inc, SAYAL, canadarobotix
**SD Card** - Same as raspberry pi, Canada Computer, Best Buy, Wall Mart, Shoppers Drug Mart
**Power Adapter** - Looking for 2amp+ MicroUSB adapters (Cell Phone chargers).  probably same place SD Cards are sold should have something
**USB WiFi** - This is a tough one nothing i know of at the moment but your looking for devices that run  the ath9k_htc, rt2800usb  or  rtl8192cu driver.. You can check them against wikidevi.com but watch the hardware version number

**Comment by Shrinks99** [comment]
This issue is a little dated but important nonetheless!  Because there is no "standard mesh hardware" in the world and we are now targeting this workshop to people outside of Toronto Mesh I am moving to close this issue in favour of each presenter taking care of this themselves should they want to provide people with a list of what their specific community network.  In the near future we may chose to create a module that deals with the LibreRouter and should that be the case having a list of mesh hardware that we recommend may come up however until it does I'm saying this issue should be closed.

**Comment by benhylau** [comment]
I think a global list. If you have all these hardware you can run anything. Then individual modules try to reference that list. If you want to add new hardware, think very hard about it!

**Comment by Shrinks99** [comment]
Is it worth trying to make an official sheet that shows this off or should that just be the approach to choosing workshop hardware explained in the course design document?

**Comment by Shrinks99** [comment]
This issue is being closed in favour of a dedicated section in the course design guidelines #71  document as decided upon in today's workshop call.
